### ISSUE TITLE
Why zsh?

### ISSUE THREAD

**Issue by fortierq** [qdm12/latexdevcontainer#21]
I have a hard time using zsh instead of bash in my GitHub actions.
For example, this is working in bash but not zsh (test file extension) :
```
if [ "${file: -4}" == ".tex" ]; then
  ...
fi
```
Apparently bash is existing in your image, so I wonder why you would use zsh?

**Comment by qdm12** [comment]
Because zsh together with oh-my-zsh offer a lot more options like plugins and theming. Apple also changed their default shell from bash to zsh.

From my standpoint, I usually work with Alpine containers which comes with ash instead of bash so I rarely use bash script and use `/bin/sh` scripts which work on everything (although it's more limited).

Now I could explore options to change the default shell to bash for a example with an env variable, would you be interested? I'm a bit overloaded currently, so feel free to do a PR to [this file](https://github.com/qdm12/latexdevcontainer/blob/master/shell/.welcome.sh) or to the [base image's zshrc](https://github.com/qdm12/basedevcontainer/blob/master/shell/.zshrc) if you want this merged faster 😉

**Comment by qdm12** [comment]
Also maybe use shebang lines for the bash scripts? That way bash will be used for these. That doesn't work for in the shell commands though.

**Comment by fortierq** [comment]
Thanks for your answer. I had a very hard time adding minted (syntax highlighting of code inside latex) to the latex container and thought it was because of zsh, but ultimately not.
I managed to fix my problem on a local docker image, but somehow it does not work with github action... Minted is a pain.
