### ISSUE TITLE
arm64 image variant

### ISSUE THREAD

**Issue by moritzj29** [qdm12/latexdevcontainer#23]
Hello,

would it be possible to add an `arm64` variant of the image? According to https://tug.org/texlive/doc/texlive-en/texlive-en.html#x1-230003.2.1 TeXLive is available for 32-bit and 64-bit ARM platforms as well.

I built the ARM image myself based on the Dockerfile. First of all I needed to add

```
RUN useradd --shell=/bin/zsh vscode
```

since the `vscode` user was not found otherwise. I'm wondering why this is not needed in the Dockerfile in the repo??

Also the `PATH` variable needs to be adjusted:
```
ENV PATH="${PATH}:/usr/local/texlive/${TEXLIVE_VERSION}/bin/aarch64-linux"
```
But I'm not sure how to adjust this dynamically to the build platform...

I think especially with Apple transitioning to ARM architecture, this will be interesting for some other people as well. In my case, the `linux/amd64` image was failing when previewing the PDFs.

**Comment by Barlerer** [comment]
I would also ask for this!

**Comment by qdm12** [comment]
> since the vscode user was not found otherwise. I'm wondering why this is not needed in the Dockerfile in the repo??

Yes that's because I forgot to pin the base dev container image which runs as root since a few months ago. That got changed now to run as root and also to have a pinned version to prevent future surprises!

**Comment by qdm12** [comment]
The image should be built for arm64 since commit 4031e45f2cd9e09db5c60dd3a80e391fa9ef7a2f
You can track the [build here](https://github.com/qdm12/latexdevcontainer/runs/5149798740?check_suite_focus=true) it might take several minutes to complete, or you can build it yourself with `docker build -t qmcgaw/latexdevcontainer https://github.com/qdm12/latexdevcontainer.git` but that'll take some time too.

**Comment by moritzj29** [comment]
awesome 🚀
